# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Leak Detector Prototype'

  # Specify what SDK version to use when compiling
  app.sdk_version = "10.9"

  # And specify what versions of OS X we want to support
  app.deployment_target = "10.7"

  app.frameworks = ['Foundation', 'AppKit', 'CoreGraphics', 'WebKit']

  # Sets the app as a background app (does not appear in Dock)
  # Note: Background apps are still allowed to have utility windows
  # and this is standard practice for "status bar" apps
  app.info_plist['LSUIElement'] = true
end
